sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t evakung/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true evakung/docker-react npm run test
before_deploy: echo $AWS_SECRET_KEY

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-044800123346"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "AKIAQU3SLUHJI6RLYEAS"
  secret_access_key: 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
