sudo: required
language: generic

# services:
#   - docker

# before_install:
#   - docker build -t evakung/docker-react -f Dockerfile.dev .

# script:
#   - docker run -e CI=true evakung/docker-react npm run test
before_deploy: echo $AWS_ACCESS_KEY

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-044800123346"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: "AKIAQU3SLUHJDAIHNWVX"
  secret_access_key:
    secure: "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"
